import { React } from 'react';

const Content = (props) => {
  //const { name } = props;
  return (
    <div className="content mdc-typography">
      <h1 className="mdc-typography--headline3">Welcome</h1>
      <p className="mdc-typography--subtitle2"> A wonderfull graphics</p>
      <h3>Section 1</h3>
      <p>
        Lorem ipsum dolor sit amet, consectetur adipiscing elit. Phasellus non nulla lectus. In vel nunc sit amet purus congue venenatis. Pellentesque viverra laoreet nulla non aliquam. Nulla efficitur tincidunt libero vitae tincidunt. Morbi eleifend bibendum felis. Curabitur pellentesque diam eros, ac rhoncus sem semper vel. Duis a orci a sapien bibendum imperdiet. Nunc sagittis sem quis volutpat porttitor. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Nullam euismod elit id efficitur tincidunt. In blandit cursus magna eu accumsan. Donec suscipit tortor vel libero condimentum, tincidunt porta diam tempor.

        Quisque rutrum arcu commodo nisl cursus dictum. Nunc sagittis mollis rutrum. Quisque faucibus leo eget leo malesuada euismod. Ut at consectetur orci. Integer imperdiet neque eu felis elementum ornare. Vivamus nec condimentum libero, vitae accumsan leo. Nulla et feugiat massa, sed imperdiet tortor.

        Praesent blandit leo massa, nec porttitor diam auctor eget. Duis malesuada lobortis lectus, ut dapibus nunc fringilla aliquam. Nunc rutrum nibh sed dolor sagittis volutpat. Pellentesque maximus, velit eu commodo porta, nisi mauris aliquet urna, eget convallis nisi mi eget lacus. Vestibulum vel massa eget justo ullamcorper congue vitae quis sem. Duis tempor rhoncus mi, nec feugiat ex dictum sed. Integer sed elit sit amet diam gravida lacinia. Nunc ac laoreet lacus, quis egestas orci. Nulla vel facilisis lacus. Curabitur placerat ac tortor quis iaculis. Ut sollicitudin elementum neque, non imperdiet nunc pulvinar sed. Morbi sit amet mauris arcu.

        Proin sodales enim velit, sit amet tempor augue fermentum et. Donec viverra est nunc, imperdiet fermentum sapien gravida nec. Suspendisse in eros ut mauris eleifend varius vel vitae tortor. Nulla non velit vel ligula ullamcorper viverra. Suspendisse ut ultrices dui. Nam augue orci, interdum quis finibus ut, accumsan quis sem. Donec nec vulputate metus, ultrices viverra odio. Praesent sed mattis augue. Nam sed diam nulla. Mauris elit quam, accumsan ac sem eget, suscipit mattis justo. Aliquam blandit eget erat sit amet gravida. Sed placerat, purus sit amet aliquam dapibus, arcu mauris lacinia enim, sed fermentum felis orci eu dui. Mauris condimentum facilisis gravida. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae;

        Etiam augue sem, interdum et ante a, laoreet ultrices ipsum. Proin et dignissim arcu. Sed aliquam et massa ac interdum. Cras eu nisi non metus aliquet sollicitudin. Aliquam at tincidunt erat, feugiat egestas libero. Pellentesque tempus felis magna, vitae vehicula mi rhoncus et. Praesent porttitor orci lectus, id imperdiet risus sodales eget. Vestibulum sit amet velit non diam semper lacinia. Duis vulputate cursus ullamcorper. Mauris eu bibendum mauris, in facilisis velit. Phasellus dictum pharetra dolor nec auctor. Integer condimentum ac arcu non tristique. Pellentesque dictum ac lectus ut consequat. Curabitur faucibus est eu efficitur dapibus. Suspendisse dictum tellus sit amet nunc posuere, nec euismod mauris volutpat.
      </p>
      <h3>Section 2</h3>
      <p>
        Lorem ipsum dolor sit amet, consectetur adipiscing elit. Phasellus non nulla lectus. In vel nunc sit amet purus congue venenatis. Pellentesque viverra laoreet nulla non aliquam. Nulla efficitur tincidunt libero vitae tincidunt. Morbi eleifend bibendum felis. Curabitur pellentesque diam eros, ac rhoncus sem semper vel. Duis a orci a sapien bibendum imperdiet. Nunc sagittis sem quis volutpat porttitor. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Nullam euismod elit id efficitur tincidunt. In blandit cursus magna eu accumsan. Donec suscipit tortor vel libero condimentum, tincidunt porta diam tempor.

        Quisque rutrum arcu commodo nisl cursus dictum. Nunc sagittis mollis rutrum. Quisque faucibus leo eget leo malesuada euismod. Ut at consectetur orci. Integer imperdiet neque eu felis elementum ornare. Vivamus nec condimentum libero, vitae accumsan leo. Nulla et feugiat massa, sed imperdiet tortor.

        Praesent blandit leo massa, nec porttitor diam auctor eget. Duis malesuada lobortis lectus, ut dapibus nunc fringilla aliquam. Nunc rutrum nibh sed dolor sagittis volutpat. Pellentesque maximus, velit eu commodo porta, nisi mauris aliquet urna, eget convallis nisi mi eget lacus. Vestibulum vel massa eget justo ullamcorper congue vitae quis sem. Duis tempor rhoncus mi, nec feugiat ex dictum sed. Integer sed elit sit amet diam gravida lacinia. Nunc ac laoreet lacus, quis egestas orci. Nulla vel facilisis lacus. Curabitur placerat ac tortor quis iaculis. Ut sollicitudin elementum neque, non imperdiet nunc pulvinar sed. Morbi sit amet mauris arcu.

        Proin sodales enim velit, sit amet tempor augue fermentum et. Donec viverra est nunc, imperdiet fermentum sapien gravida nec. Suspendisse in eros ut mauris eleifend varius vel vitae tortor. Nulla non velit vel ligula ullamcorper viverra. Suspendisse ut ultrices dui. Nam augue orci, interdum quis finibus ut, accumsan quis sem. Donec nec vulputate metus, ultrices viverra odio. Praesent sed mattis augue. Nam sed diam nulla. Mauris elit quam, accumsan ac sem eget, suscipit mattis justo. Aliquam blandit eget erat sit amet gravida. Sed placerat, purus sit amet aliquam dapibus, arcu mauris lacinia enim, sed fermentum felis orci eu dui. Mauris condimentum facilisis gravida. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae;

        Etiam augue sem, interdum et ante a, laoreet ultrices ipsum. Proin et dignissim arcu. Sed aliquam et massa ac interdum. Cras eu nisi non metus aliquet sollicitudin. Aliquam at tincidunt erat, feugiat egestas libero. Pellentesque tempus felis magna, vitae vehicula mi rhoncus et. Praesent porttitor orci lectus, id imperdiet risus sodales eget. Vestibulum sit amet velit non diam semper lacinia. Duis vulputate cursus ullamcorper. Mauris eu bibendum mauris, in facilisis velit. Phasellus dictum pharetra dolor nec auctor. Integer condimentum ac arcu non tristique. Pellentesque dictum ac lectus ut consequat. Curabitur faucibus est eu efficitur dapibus. Suspendisse dictum tellus sit amet nunc posuere, nec euismod mauris volutpat.
      </p>
      <h3>Section 3</h3>
      <p>
        Lorem ipsum dolor sit amet, consectetur adipiscing elit. Phasellus non nulla lectus. In vel nunc sit amet purus congue venenatis. Pellentesque viverra laoreet nulla non aliquam. Nulla efficitur tincidunt libero vitae tincidunt. Morbi eleifend bibendum felis. Curabitur pellentesque diam eros, ac rhoncus sem semper vel. Duis a orci a sapien bibendum imperdiet. Nunc sagittis sem quis volutpat porttitor. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Nullam euismod elit id efficitur tincidunt. In blandit cursus magna eu accumsan. Donec suscipit tortor vel libero condimentum, tincidunt porta diam tempor.

        Quisque rutrum arcu commodo nisl cursus dictum. Nunc sagittis mollis rutrum. Quisque faucibus leo eget leo malesuada euismod. Ut at consectetur orci. Integer imperdiet neque eu felis elementum ornare. Vivamus nec condimentum libero, vitae accumsan leo. Nulla et feugiat massa, sed imperdiet tortor.

        Praesent blandit leo massa, nec porttitor diam auctor eget. Duis malesuada lobortis lectus, ut dapibus nunc fringilla aliquam. Nunc rutrum nibh sed dolor sagittis volutpat. Pellentesque maximus, velit eu commodo porta, nisi mauris aliquet urna, eget convallis nisi mi eget lacus. Vestibulum vel massa eget justo ullamcorper congue vitae quis sem. Duis tempor rhoncus mi, nec feugiat ex dictum sed. Integer sed elit sit amet diam gravida lacinia. Nunc ac laoreet lacus, quis egestas orci. Nulla vel facilisis lacus. Curabitur placerat ac tortor quis iaculis. Ut sollicitudin elementum neque, non imperdiet nunc pulvinar sed. Morbi sit amet mauris arcu.

        Proin sodales enim velit, sit amet tempor augue fermentum et. Donec viverra est nunc, imperdiet fermentum sapien gravida nec. Suspendisse in eros ut mauris eleifend varius vel vitae tortor. Nulla non velit vel ligula ullamcorper viverra. Suspendisse ut ultrices dui. Nam augue orci, interdum quis finibus ut, accumsan quis sem. Donec nec vulputate metus, ultrices viverra odio. Praesent sed mattis augue. Nam sed diam nulla. Mauris elit quam, accumsan ac sem eget, suscipit mattis justo. Aliquam blandit eget erat sit amet gravida. Sed placerat, purus sit amet aliquam dapibus, arcu mauris lacinia enim, sed fermentum felis orci eu dui. Mauris condimentum facilisis gravida. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae;

        Etiam augue sem, interdum et ante a, laoreet ultrices ipsum. Proin et dignissim arcu. Sed aliquam et massa ac interdum. Cras eu nisi non metus aliquet sollicitudin. Aliquam at tincidunt erat, feugiat egestas libero. Pellentesque tempus felis magna, vitae vehicula mi rhoncus et. Praesent porttitor orci lectus, id imperdiet risus sodales eget. Vestibulum sit amet velit non diam semper lacinia. Duis vulputate cursus ullamcorper. Mauris eu bibendum mauris, in facilisis velit. Phasellus dictum pharetra dolor nec auctor. Integer condimentum ac arcu non tristique. Pellentesque dictum ac lectus ut consequat. Curabitur faucibus est eu efficitur dapibus. Suspendisse dictum tellus sit amet nunc posuere, nec euismod mauris volutpat.
      </p>
      <h3>Section 4</h3>
      <p>
        Lorem ipsum dolor sit amet, consectetur adipiscing elit. Phasellus non nulla lectus. In vel nunc sit amet purus congue venenatis. Pellentesque viverra laoreet nulla non aliquam. Nulla efficitur tincidunt libero vitae tincidunt. Morbi eleifend bibendum felis. Curabitur pellentesque diam eros, ac rhoncus sem semper vel. Duis a orci a sapien bibendum imperdiet. Nunc sagittis sem quis volutpat porttitor. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Nullam euismod elit id efficitur tincidunt. In blandit cursus magna eu accumsan. Donec suscipit tortor vel libero condimentum, tincidunt porta diam tempor.

        Quisque rutrum arcu commodo nisl cursus dictum. Nunc sagittis mollis rutrum. Quisque faucibus leo eget leo malesuada euismod. Ut at consectetur orci. Integer imperdiet neque eu felis elementum ornare. Vivamus nec condimentum libero, vitae accumsan leo. Nulla et feugiat massa, sed imperdiet tortor.

        Praesent blandit leo massa, nec porttitor diam auctor eget. Duis malesuada lobortis lectus, ut dapibus nunc fringilla aliquam. Nunc rutrum nibh sed dolor sagittis volutpat. Pellentesque maximus, velit eu commodo porta, nisi mauris aliquet urna, eget convallis nisi mi eget lacus. Vestibulum vel massa eget justo ullamcorper congue vitae quis sem. Duis tempor rhoncus mi, nec feugiat ex dictum sed. Integer sed elit sit amet diam gravida lacinia. Nunc ac laoreet lacus, quis egestas orci. Nulla vel facilisis lacus. Curabitur placerat ac tortor quis iaculis. Ut sollicitudin elementum neque, non imperdiet nunc pulvinar sed. Morbi sit amet mauris arcu.

        Proin sodales enim velit, sit amet tempor augue fermentum et. Donec viverra est nunc, imperdiet fermentum sapien gravida nec. Suspendisse in eros ut mauris eleifend varius vel vitae tortor. Nulla non velit vel ligula ullamcorper viverra. Suspendisse ut ultrices dui. Nam augue orci, interdum quis finibus ut, accumsan quis sem. Donec nec vulputate metus, ultrices viverra odio. Praesent sed mattis augue. Nam sed diam nulla. Mauris elit quam, accumsan ac sem eget, suscipit mattis justo. Aliquam blandit eget erat sit amet gravida. Sed placerat, purus sit amet aliquam dapibus, arcu mauris lacinia enim, sed fermentum felis orci eu dui. Mauris condimentum facilisis gravida. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae;

        Etiam augue sem, interdum et ante a, laoreet ultrices ipsum. Proin et dignissim arcu. Sed aliquam et massa ac interdum. Cras eu nisi non metus aliquet sollicitudin. Aliquam at tincidunt erat, feugiat egestas libero. Pellentesque tempus felis magna, vitae vehicula mi rhoncus et. Praesent porttitor orci lectus, id imperdiet risus sodales eget. Vestibulum sit amet velit non diam semper lacinia. Duis vulputate cursus ullamcorper. Mauris eu bibendum mauris, in facilisis velit. Phasellus dictum pharetra dolor nec auctor. Integer condimentum ac arcu non tristique. Pellentesque dictum ac lectus ut consequat. Curabitur faucibus est eu efficitur dapibus. Suspendisse dictum tellus sit amet nunc posuere, nec euismod mauris volutpat.
      </p>
    </div>
  );
};

export default Content;